CREATE DATABASE SGDUSERDB;
CREATE USER 'APPSERVERUSER'@'%' IDENTIFIED BY '123';
GRANT ALL PRIVILEGES ON SGDUSERDB.* TO 'APPSERVERUSER'@'%';
FLUSH PRIVILEGES;

USE SGDUSERDB;

CREATE TABLE `GROUP` (
    Id INT PRIMARY KEY AUTO_INCREMENT,
    `Name` VARCHAR(255) NOT NULL
);

CREATE TABLE USER (
    Id INT PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(255) NOT NULL,
    `password` VARCHAR(255) NOT NULL,
    groupPermId INT,
    CONSTRAINT fk_groupId FOREIGN KEY (groupPermId) REFERENCES `GROUP`(Id)
);

INSERT INTO `GROUP` (`Name`) VALUES ('test');
INSERT INTO USER (username, `password`, groupPermId) 
VALUES ('utest', '123', 1);
